import boothCover from "../assets/images/Mypage/boothcover.png";
import concert from "../assets/images/Mypage/concert.png";

export const boothData = [
  {
    id: 1,
    user: 1,
    day: [],
    times: [
      {
        id: 1,
        created_at: "2023-05-02 08:00",
        updated_at: "2023-05-02 08:00",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 2,
        created_at: "2023-05-02 08:02",
        updated_at: "2023-05-02 08:02",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 3,
        created_at: "2023-05-02 08:04",
        updated_at: "2023-05-02 08:04",
        starttime: "null",
        finishtime: "null",
      },
    ],
    college: "포스코관",
    category: "굿즈",
    name: "멋쟁이 사자처럼",
    number: "포08",
    thumbnail: [boothCover, concert],
    opened: false,
    hashtag: "#떡고치",
    description: "멋쟁이 사자처럼 부스 소개 어쩌구 저쩌구 안녕하세요 뿡뿡",
    is_liked: true,
    is_like_count: 1,
    busy: false,
    began: false,
    wheelchair: false,
    is_show: false,
    contact: "~~kakao link",
  },
  {
    id: 2,
    user: 2,
    day: [],
    times: [
      {
        id: 1,
        created_at: "2023-05-02 08:00",
        updated_at: "2023-05-02 08:00",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 2,
        created_at: "2023-05-02 08:02",
        updated_at: "2023-05-02 08:02",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 3,
        created_at: "2023-05-02 08:04",
        updated_at: "2023-05-02 08:04",
        starttime: "null",
        finishtime: "null",
      },
    ],
    college: "정문",
    category: "음식",
    name: "멋쟁이",
    number: "포01",
    thumbnail: [boothCover, concert],
    opened: true,
    hashtag: "#떡고치",
    description: "멋쟁이 사자처럼 부스 소개 어쩌구 저쩌구 안녕하세요 뿡뿡",
    is_liked: true,
    is_like_count: 1,
    busy: true,
    began: true,
    wheelchair: true,
    is_show: false,
    contact: "~~kakao link",
  },
  {
    id: 3,
    user: 3,
    day: [],
    times: [
      {
        id: 1,
        created_at: "2023-05-02 08:00",
        updated_at: "2023-05-02 08:00",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 2,
        created_at: "2023-05-02 08:02",
        updated_at: "2023-05-02 08:02",
        starttime: "null",
        finishtime: "null",
      },
      {
        id: 3,
        created_at: "2023-05-02 08:04",
        updated_at: "2023-05-02 08:04",
        starttime: "null",
        finishtime: "null",
      },
    ],
    college: "교육관",
    category: "음식",
    name: "멋쟁이",
    number: "교01",
    thumbnail: [boothCover, concert],
    opened: true,
    hashtag: "#떡고치",
    description: "멋쟁이 사자처럼 부스 소개 어쩌구 저쩌구 안녕하세요 뿡뿡",
    is_liked: true,
    is_like_count: 1,
    busy: true,
    began: true,
    wheelchair: true,
    is_show: false,
    contact: "~~kakao link",
  },
];
